<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorRephormatApplication' => 'src/application/PhabricatorRephormatApplication.php',
    'PhabricatorRephormatImportQuery' => 'src/query/PhabricatorRephormatImportQuery.php',
    'PhabricatorRephormatImportRemarkupRule' => 'src/remarkup/PhabricatorRephormatImportRemarkupRule.php',
    'RephormatController' => 'src/controller/RephormatController.php',
    'RephormatCreateStep1Controller' => 'src/controller/RephormatCreateStep1Controller.php',
    'RephormatCreateStep2Controller' => 'src/controller/RephormatCreateStep2Controller.php',
    'RephormatHomeController' => 'src/controller/RephormatHomeController.php',
    'RephormatImport' => 'src/storage/RephormatImport.php',
    'RephormatImportEditEngine' => 'src/editor/RephormatImportEditEngine.php',
    'RephormatImportPHIDType' => 'src/phid/RephormatImportPHIDType.php',
    'RephormatViewController' => 'src/controller/RephormatViewController.php',
    'RephortmatLoadStep1Worker' => 'src/worker/RephortmatLoadStep1Worker.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorRephormatApplication' => 'PhabricatorApplication',
    'PhabricatorRephormatImportQuery' => 'PhabricatorCursorPagedPolicyAwareQuery',
    'PhabricatorRephormatImportRemarkupRule' => 'PhabricatorObjectRemarkupRule',
    'RephormatController' => 'PhabricatorController',
    'RephormatCreateStep1Controller' => 'RephormatController',
    'RephormatCreateStep2Controller' => 'RephormatController',
    'RephormatHomeController' => 'RephormatController',
    'RephormatImport' => 'PhabricatorRepositoryDAO',
    'RephormatImportEditEngine' => 'PhabricatorEditEngine',
    'RephormatImportPHIDType' => 'PhabricatorPHIDType',
    'RephormatViewController' => 'RephormatController',
    'RephortmatLoadStep1Worker' => 'PhabricatorWorker',
  ),
));
