<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ImportQuery' => 'src/query/ImportQuery.php',
    'PhabricatorRephormatApplication' => 'src/application/PhabricatorRephormatApplication.php',
    'PhabricatorRephormatDAO' => 'src/storage/PhabricatorRephormatDAO.php',
    'PhabricatorRephormatImportRemarkupRule' => 'src/remarkup/PhabricatorRephormatImportRemarkupRule.php',
    'PhabricatorRephormatSchemaSpec' => 'src/storage/PhabricatorRephormatSchemaSpec.php',
    'PhabricatorRephormatSearchEngine' => 'src/query/PhabricatorRephormatSearchEngine.php',
    'RephormatController' => 'src/controller/RephormatController.php',
    'RephormatCreateController' => 'src/controller/RephormatCreateController.php',
    'RephormatEditController' => 'src/controller/RephormatEditController.php',
    'RephormatHomeController' => 'src/controller/RephormatHomeController.php',
    'RephormatImport' => 'src/storage/RephormatImport.php',
    'RephormatImportCredentialsGitHub' => 'src/storage/RephormatImportCredentialsGitHub.php',
    'RephormatImportCredentialsGitHubPHIDType' => 'src/phid/RephormatImportCredentialsGitHubPHIDType.php',
    'RephormatImportCredentialsJira' => 'src/storage/RephormatImportCredentialsJira.php',
    'RephormatImportCredentialsJiraPHIDType' => 'src/phid/RephormatImportCredentialsJiraPHIDType.php',
    'RephormatImportEditEngine' => 'src/editor/RephormatImportEditEngine.php',
    'RephormatImportPHIDType' => 'src/phid/RephormatImportPHIDType.php',
    'RephormatStep2Controller' => 'src/controller/RephormatStep2Controller.php',
    'RephormatViewController' => 'src/controller/RephormatViewController.php',
    'RephortmatLoadStep1Worker' => 'src/worker/RephortmatLoadStep1Worker.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ImportQuery' => 'PhabricatorCursorPagedPolicyAwareQuery',
    'PhabricatorRephormatApplication' => 'PhabricatorApplication',
    'PhabricatorRephormatDAO' => 'PhabricatorLiskDAO',
    'PhabricatorRephormatImportRemarkupRule' => 'PhabricatorObjectRemarkupRule',
    'PhabricatorRephormatSchemaSpec' => 'PhabricatorConfigSchemaSpec',
    'PhabricatorRephormatSearchEngine' => 'PhabricatorApplicationSearchEngine',
    'RephormatController' => 'PhabricatorController',
    'RephormatCreateController' => 'RephormatController',
    'RephormatEditController' => 'RephormatController',
    'RephormatHomeController' => 'RephormatController',
    'RephormatImport' => array(
      'PhabricatorRephormatDAO',
      'PhabricatorPolicyInterface',
    ),
    'RephormatImportCredentialsGitHub' => 'PhabricatorRephormatDAO',
    'RephormatImportCredentialsGitHubPHIDType' => 'PhabricatorPHIDType',
    'RephormatImportCredentialsJira' => 'PhabricatorRephormatDAO',
    'RephormatImportCredentialsJiraPHIDType' => 'PhabricatorPHIDType',
    'RephormatImportEditEngine' => 'PhabricatorEditEngine',
    'RephormatImportPHIDType' => 'PhabricatorPHIDType',
    'RephormatStep2Controller' => 'RephormatController',
    'RephormatViewController' => 'RephormatController',
    'RephortmatLoadStep1Worker' => 'PhabricatorWorker',
  ),
));
